# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Kiran V Garimella
title: Senior Computational Scientist
email: kiran@broadinstitute.org
#website: www.github.com/sproogen/resume-theme

# Social links
twitter_username: KiranGarimella
github_username:  kvg
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: kiran-garimella-02aa8529
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a research scientist in the Data Sciences Platform at the Broad Institute.  I run the <mark>Long Read Methods and Applications</mark> group which develops novel tools and applications for single molecule sequencing instruments.

  Prior to this, I was a DPhil student (2011-2016) and post-doc (2016-2018) at the University of Oxford under the guidance of Gil McVean.  I worked on combining long read and short read data to improve de novo assembly.  I applied these methods to de novo mutation discovery in malaria experimental crosses.

# Experience Section
experience_title: Selected Publications

# Projects Section
# projects_title: Projects

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in extreme genomic diversity, graphical models, and software engineering, some of my other interests are:
   - Banjo
   - Sculling
   - Making the perfect iced latte
   - [That this exists](https://www.youtube.com/watch?v=_hpU6UEq8hA)

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
